2024-08-08 12:08:32,678 INFO    MainThread:4728 [wandb_setup.py:_flush():76] Current SDK version is 0.17.5
2024-08-08 12:08:32,678 INFO    MainThread:4728 [wandb_setup.py:_flush():76] Configure stats pid to 4728
2024-08-08 12:08:32,678 INFO    MainThread:4728 [wandb_setup.py:_flush():76] Loading settings from C:\Users\olivi\.config\wandb\settings
2024-08-08 12:08:32,678 INFO    MainThread:4728 [wandb_setup.py:_flush():76] Loading settings from C:\Users\olivi\.vscode\projects\wandb\settings
2024-08-08 12:08:32,678 INFO    MainThread:4728 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-08-08 12:08:32,678 INFO    MainThread:4728 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-08-08 12:08:32,679 INFO    MainThread:4728 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'handwrittendigit.py', 'program_abspath': 'c:\\Users\\olivi\\.vscode\\projects\\handwrittendigit.py', 'program': 'c:\\Users\\olivi\\.vscode\\projects\\handwrittendigit.py'}
2024-08-08 12:08:32,679 INFO    MainThread:4728 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-08-08 12:08:32,679 INFO    MainThread:4728 [wandb_init.py:_log_setup():529] Logging user logs to C:\Users\olivi\.vscode\projects\wandb\run-20240808_120832-0x5t4bok\logs\debug.log
2024-08-08 12:08:32,679 INFO    MainThread:4728 [wandb_init.py:_log_setup():530] Logging internal logs to C:\Users\olivi\.vscode\projects\wandb\run-20240808_120832-0x5t4bok\logs\debug-internal.log
2024-08-08 12:08:32,679 INFO    MainThread:4728 [wandb_init.py:init():569] calling init triggers
2024-08-08 12:08:32,679 INFO    MainThread:4728 [wandb_init.py:init():576] wandb.init called with sweep_config: {}
config: {'epochs': 5, 'batch_size': 16, 'lr': 0.001, 'width': 1024}
2024-08-08 12:08:32,679 INFO    MainThread:4728 [wandb_init.py:init():619] starting backend
2024-08-08 12:08:32,679 INFO    MainThread:4728 [wandb_init.py:init():623] setting up manager
2024-08-08 12:08:32,679 INFO    MainThread:4728 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-08-08 12:08:32,679 INFO    MainThread:4728 [wandb_init.py:init():631] backend started and connected
2024-08-08 12:08:32,688 INFO    MainThread:4728 [wandb_init.py:init():720] updated telemetry
2024-08-08 12:08:32,760 INFO    MainThread:4728 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-08-08 12:08:33,303 INFO    MainThread:4728 [wandb_run.py:_on_init():2435] communicating current version
2024-08-08 12:08:33,879 INFO    MainThread:4728 [wandb_run.py:_on_init():2444] got version response upgrade_message: "wandb version 0.17.6 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-08-08 12:08:33,880 INFO    MainThread:4728 [wandb_init.py:init():804] starting run threads in backend
2024-08-08 12:08:34,077 WARNING MainThread:4728 [wandb_init.py:init():1185] interrupted
Traceback (most recent call last):
  File "C:\Users\olivi\AppData\Roaming\Python\Python312\site-packages\wandb\sdk\wandb_init.py", line 1181, in init
    return wi.init()
           ^^^^^^^^^
  File "C:\Users\olivi\AppData\Roaming\Python\Python312\site-packages\wandb\sdk\wandb_init.py", line 846, in init
    run._on_start()
  File "C:\Users\olivi\AppData\Roaming\Python\Python312\site-packages\wandb\sdk\wandb_run.py", line 2467, in _on_start
    self._backend.interface.publish_python_packages(working_set())
  File "C:\Users\olivi\AppData\Roaming\Python\Python312\site-packages\wandb\sdk\interface\interface.py", line 295, in publish_python_packages
    for pkg in working_set:
  File "C:\Users\olivi\AppData\Roaming\Python\Python312\site-packages\wandb\util.py", line 1887, in working_set
    yield InstalledDistribution(key=d.metadata["Name"], version=d.version)
                                    ^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\importlib\metadata\__init__.py", line 444, in metadata
    self.read_text('METADATA')
  File "C:\Program Files\Python312\Lib\importlib\metadata\__init__.py", line 819, in read_text
    return self._path.joinpath(filename).read_text(encoding='utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\pathlib.py", line 1027, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
KeyboardInterrupt
2024-08-08 12:08:37,326 WARNING MsgRouterThr:4728 [router.py:message_loop():77] message_loop has been closed
